# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

title: Fred's Blog
description: Welcome to my blog. After I teach myself something, I will try to create a blog post explaining to a relative noob the concept or tool. After learning something, the tricky parts are evident, but this fades with experience. I will try to emphasize what originally stumped me. Personally, this blog serves the same function as a homework assignment for a class: forced recall and accuracy. Other personal benefits include, finding gaps in my own knowledge by walking through every step and practice writing clearly and concisely.
github_username: fredc1

# Email and twitter are optional:
email:
twitter_username:

# Set this to true to get LaTeX math equation support
use_math: true

# Add your Google Analytics ID here if you have one and want to use it
google_analytics:

# Everything below here can be ignored, unless you want to change the theme entirely
theme: minima
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-octicons
  - jekyll-github-metadata

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
